from sb3_contrib import MaskablePPO
from stable_baselines3.common.callbacks import CheckpointCallback
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

from train_boosted import (
    CHECKPOINT_DIR,
    CHECKPOINT_FREQ,
    TENSORBOARD_LOG_DIR,
    VEC_NORMALIZE_OUTPUT,
    DetailedMetricsCallback,  # FIXED: Imported the correct callback name
    StableMaskableMultiInputActorCriticPolicy,
    make_env,
)

# FIXED: Points exactly to the model generated by your train_boosted.py script
SOURCE_MODEL = "ppo_blockudoku_survival_v2"

# STRATEGY: Save this secondary phase as v3 so you preserve your old files safely
OUTPUT_MODEL = "ppo_blockudoku_survival_v3"
VEC_NORMALIZE_OUTPUT_V3 = "vecnormalize_blockudoku_survival_v3.pkl"

ADDITIONAL_TIMESTEPS = 5_000_000


def main():
    print("Resuming survival-focused MaskablePPO training...")
    print("Loading environment with saved reward normalization statistics...")

    # FIXED: Reconstruct the environment by loading your previous normalization stats
    # This prevents reward scales from resetting back to zero.
    base_venv = DummyVecEnv([make_env])
    env = VecNormalize.load(VEC_NORMALIZE_OUTPUT, base_venv)
    env.training = True
    env.norm_obs = False  # Keep synchronized with train_boosted configuration

    valid_actions = int(env.envs[0].action_masks().sum())
    print(f"Action mask active. Legal actions on reset: {valid_actions}")

    print(f"Loading existing model from {SOURCE_MODEL}.zip...")
    model = MaskablePPO.load(
        SOURCE_MODEL,
        env=env,
        custom_objects={"policy_class": StableMaskableMultiInputActorCriticPolicy},
    )
    model.tensorboard_log = TENSORBOARD_LOG_DIR
    print("Model loaded successfully.")

    print(f"Training for {ADDITIONAL_TIMESTEPS:,} more timesteps...")
    callbacks = [
        DetailedMetricsCallback(),  # FIXED: Updated callback invocation
        CheckpointCallback(
            save_freq=CHECKPOINT_FREQ,
            save_path=CHECKPOINT_DIR,
            name_prefix="ppo_survival_v3",
        ),
    ]
    
    model.learn(
        total_timesteps=ADDITIONAL_TIMESTEPS,
        reset_num_timesteps=False,  # CRITICAL: Keeps your timeline consecutive in TensorBoard
        tb_log_name="MaskablePPO",
        callback=callbacks,
        progress_bar=True,
    )

    model.save(OUTPUT_MODEL)
    env.save(VEC_NORMALIZE_OUTPUT_V3)
    print(f"\nTraining complete. Updated model saved as {OUTPUT_MODEL}.zip")
    print(f"Updated VecNormalize stats saved as {VEC_NORMALIZE_OUTPUT_V3}")
    print(f"TensorBoard logs are in: {TENSORBOARD_LOG_DIR}")
    print(f"Open TensorBoard with: tensorboard --logdir {TENSORBOARD_LOG_DIR}")
    env.close()


if __name__ == "__main__":
    main()